spring:
  application:
    name: open-gateway-server  #服务名
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8888
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery.clsaa.com/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

zuul:
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000